version: "3.8"

services:
  server-node:
    container_name: "server_container"
    build:
      context: server
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    networks:
      - hello-build
  client:
    container_name: "client_container"
    build:
      context: client
      dockerfile: Dockerfile
    links:
      - "server:server"
    ports:
      - "3000:3000"
    networks:
      - hello-build

networks:
  hello-build:
    driver: bridge

